[project]
name = "gpt-assistants-playground"
version = "0.1.0"
description = ""
authors = []
readme = "README.md"
requires-python = ">=3.13,<3.14"
dependencies = [
    "anthropic (>=0.62.0,<0.63.0)",
    "audioop-lts (>=0.2.2,<0.3.0)",
    "azure-search-documents (>=11.5.3,<12.0.0)",
    "fal-client (>=0.7.0,<0.8.0)",
    "googlemaps (>=4.10.0,<5.0.0)",
    "gradio (==5.42.0)",
    "groq (>=0.31.0,<0.32.0)",
    "jinja2 (>=3.1.6,<4.0.0)",
    "markdown (>=3.8.2,<4.0.0)",
    "moviepy (>=1.0.3,<2.0.0)",
    "opencv-python (>=4.12.0.88,<5.0.0.0)",
    "openai (>=1.99.9,<2.0.0)",
    "openai (>=1.99.9,<2.0.0)",
    "prefect (==3.1.13)",
    "py-trees (>=2.3.0,<3.0.0)",
    "pyautogui (>=0.9.54,<0.10.0)",
    "pymupdf (>=1.26.3,<2.0.0)",
    "pytest (>=8.4.1,<9.0.0)",
    "python-docx (>=1.2.0,<2.0.0)",
    "python-dotenv (>=1.1.1,<2.0.0)",
    "python-pptx (>=1.0.2,<2.0.0)",
    "scipy (>=1.16.1,<2.0.0)",
    "tiktoken (>=0.11.0,<0.12.0)",
    "twitter-api-client (>=0.10.22,<0.11.0)",
    "wikipedia (>=1.4.0,<2.0.0)",
    "youtube-transcript-api (>=1.2.2,<2.0.0)",
    "peewee (>=3.18.2,<4.0.0)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
